Repository SENG426-Summer-2022/vega-web-master, pull requests merged in 2022-07, with the labels that each got.

#31 11 contact us form
  package-lock.json
  package.json
  server/controller/ContactController.js
  server/index.js
  server/package-lock.json
  src/App.js
  src/__tests__/ContactUs.test.js
  src/components/UI/organisms/ContactUsForm.js
  src/components/pages/ContactUs.js
  src/components/pages/Login.js
  src/components/pages/SignUp.js
  src/components/pages/UserRegistration.js
  src/components/templates/FormPageLayout.js
  src/service/ContactUs/ContactService.js
Labels: bug

#16 Admin Panel UI does not reflect user state
  server/controller/FileUploadController.js
  src/__tests__/AdminPanel.test.js
  src/components/UI/organisms/LoginUser.js
  src/components/pages/AdminPanel.js
  src/components/pages/Login.js
  src/service/AdminPanel/AdminPanel.js
  src/service/auth/AuthenticationManager.js
Labels: bug, Medium

#41 33 add user crud develop
  server/controller/AdminPanelController.js
  server/services/AdminPanelAPI.js
  server/services/HTTPRequestAPI.js
  src/App.js
  src/__tests__/AdminPanel.test.js
  src/__tests__/AdminUserManagement.test.js
  src/components/UI/molecules/DeleteUser.js
  src/components/UI/molecules/VenusNavBar.js
  src/components/UI/organisms/UpdateUserForm.js
  src/components/pages/AdminPanel.js
  src/components/pages/AdminUserManagement.js
  src/service/AdminPanel/AdminPanel.js
  src/service/BaseAPI.js
Labels: Feature
